#
# This project Makefile helps build and run the Photos application.
#

# C++ compiler to use
CXX=g++

# C++ Warning flags to use
CXX_WARNINGS = -Wall -Wextra -pedantic-errors

# Qt modules we want to compile in
QT_MODULES = Qt5Core Qt5Widgets

# Generates the Qt flags for the specific modules we want to use
QT_FLAGS = $(shell pkg-config --cflags --libs $(QT_MODULES)) -fPIC

# Use -O0 for development to make debugging easier.
OPTIMIZATION_FLAG = -O0

# Final C++ flags to use
CXX_FLAGS = $(CXX_WARNINGS) -std=c++11 $(OPTIMIZATION_FLAG) $(QT_FLAGS)

# Source files and entry file (contains main()) to compile
SRC_FILES=src/mainwindow.cpp
SRC_ENTRY=src/main.cpp

# Folder and filename to build the executable file to
BIN_FOLDER = bin
BUILD_OUTFILE = photos

#
# Phony targets a.k.a run the makefile task
# even if files by these names exist in the
# directory.
#
.PHONY: all build clean

#
# Default target: Builds and runs the project.
#
all: build run

#
# Build target: Builds the project by creating a bin/
# folder and compiling the app into a `photos` executable
# inside of it.
#
build: $(SRC_ENTRY) $(SRC_FILES)
	@mkdir -p $(BIN_FOLDER)
	@$(CXX) $(CXX_FLAGS) $(SRC_ENTRY) $(SRC_FILES) -o $(BIN_FOLDER)/$(BUILD_OUTFILE)

run:
	@./bin/photos

#
# Clean target: Removes the bin folder that is generated
# from the build target.
#
clean:
	@rm -rf $(BIN_FOLDER)
